export const formation = [
    {
        id: 1,
        title: "Projet Réseau 1",
        description: "Projet de réseau pour la mise en place d'un serveur de fichier et d'un serveur web",
        startdate: "2019-01-01",
        enddate: "2019-02-01",
        stage: "non",
        Competences: ["Reseau", "Serveur", "Web", "Fichier"],
    },

    {
        id: 2,
        title: "Developpement POO",
        description: "Developpement d'un programme de gestion de stock en POO",
        startdate: "2019-02-01",
        enddate: "2019-03-01",
        stage: "non",
        Competences: ["POO", "Programmation", "Stock"],
    },
    {
        id: 3,
        title: "EPSILON",
        description: "Developpement d'un site web pour une association",
        startdate: "2019-03-01",
        enddate: "2019-04-01",
        stage: "non",
        Competences: ["Web", "Site", "Association"],
    },
    {
        id: 4,
        title: "Developpement Web : Agenda",
        description: "Developpement d'un agenda en ligne",
        startdate: "2019-04-01",
        enddate: "2019-05-01",
        stage: "non",
        Competences: ["Web", "Agenda", "Programmation"],
    },
    {
        id: 5,
        title: "Projet Emailling",
        description: "Developpement d'un programme d'envoi d'email",
        startdate: "2019-05-01",
        enddate: "2019-06-01",
        stage: "non",
        Competences: ["Email", "Programmation", "Web"],
    },
    {
        id: 6,
        title: "Projet Python : ChessGame ",
        description: "Developpement d'un jeu d'echec en python",
        startdate: "2019-06-01",
        enddate: "2019-07-01",
        stage: "non",
        Competences: ["Python", "Jeu", "Programmation"],
    },
    {
        id: 7,
        title: "Site web : Portfolio",
        description: "Developpement d'un site web pour un portfolio",
        startdate: "2019-07-01",
        enddate: "2019-08-01",
        stage: "non",
        Competences: ["Web", "Site", "Portfolio"],
    },
    {
        id: 8,
        title: "Projet BTS 1 : Restaurant Chinois",
        description: "Developpement d'un site web pour un restaurant chinois",
        startdate: "2019-08-01",
        enddate: "2019-09-01",
        stage: "non",
        Competences: ["Web", "Site", "Restaurant"],
    },
    {
        id: 9,
        title: "Projet BTS 2 : Gestion de stock",
        description: "Developpement d'un programme de gestion de stock",
        startdate: "2019-09-01",
        enddate: "2019-10-01",
        stage: "non",
        Competences: ["Programmation", "Stock"],
    },
    {
        id: 10,
        title: "Projet BTS 3 : Sauvegarde et synchronisation des données",
        description: "Developpement d'un programme de sauvegarde et synchronisation des données",
        startdate: "2019-10-01",
        enddate: "2019-11-01",
        stage: "non",
        Competences: ["Programmation", "Sauvegarde", "Données"],
    },
    {
        id: 11,
        title: "Projet Réseau 2",
        description: "Projet de réseau pour la mise en place d'un serveur de fichier et d'un serveur web",
        startdate: "2019-11-01",
        enddate: "2019-12-01",
        stage: "non",
        Competences: ["Reseau", "Serveur", "Web", "Fichier"],
    },
    {
        id: 12,
        title: "Developpement de mini jeux",
        description: "Developpement de mini jeux en javascript",
        startdate: "2019-12-01",
        enddate: "2020-01-01",
        stage: "oui",
        Competences: ["Javascript", "Jeu", "Programmation"],
    },
    {
        id: 13,
        title: "Administration site 1",
        description: "Administration d'un site web",
        startdate: "2020-01-01",
        enddate: "2020-02-01",
        stage: "oui",
        Competences: ["Web", "Site", "Administration"],
    },
    {
        id: 14,
        title: "Administration site 2",
        description: "Administration d'un site web",
        startdate: "2020-02-01",
        enddate: "2020-03-01",
        stage: "oui",
        Competences: ["Web", "Site", "Administration"],
    },
    {
        id: 15,
        title: "Developpement site statique",
        description: "Developpement d'un site web statique",
        startdate: "2020-03-01",
        enddate: "2020-04-01",
        stage: "oui",
        Competences: ["Web", "Site", "Statique"],
    },
    {
        id: 16,
        title: "Developpement Chatbot",
        description: "Developpement d'un chatbot",
        startdate: "2020-04-01",
        enddate: "2020-05-01",
        stage: "oui",
        Competences: ["Web", "Site", "Statique"],
    },
];
