export const formation = [
   {
      id: 1,
      titre: "Acquisition leads",
      description: "Création d'un leads pour un site de réservation de voyage exclusivement reservé aux entreprises",
      categorie: [{ id: "c3" }, { id: "c4" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 2,
      titre: "Audit Ilévia / VLille / Booking /",
      description: "Audit sur ceci",
      categorie: [{ id: "c2" }, { id: "c3" }, { id: "c4" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 3,
      titre: "WorkShop",
      description: "WorkShop réalisé en 1ére et deuxième année",
      categorie: [{ id: "c1" }, { id: "c3" }, { id: "c4" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 4,
      titre: "Projet communication",
      description: "Réalisation d'un projet de communication sur le bassin d'Arcachon / Magi / Bonne Maman",
      categorie: [{ id: "c2" }, { id: "c3" }, { id: "c4" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 5,
      titre: "Projet Python",
      description: "Réalisation de plusieurs jeux, simulation poulailler, simulation création sandwich subaway, et jeu d'échec, le tout fait en terminal",
      categorie: [{ id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 6,
      titre: "Projet Agenda",
      description: "Réalisation d'un agenda (côté front), création d'une interface agréable d'un agenda scolaire.",
      categorie: [{ id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 7,
      titre: "Réalisation d'une bdd pour un site d'informations",
      description: "Réalisation d'une bdd pour un site d'informations sur le tour de France ET de l'affichage sur site web",
      categorie: [{ id: "c1" }, { id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 8,
      titre: "Réalisation d'une bdd pour un voyage prédéfini",
      description: "Réalisation d'une bdd pour un site de voyage en php/mysql afin de réserver un voyage",
      categorie: [{ id: "c1" }, { id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 9,
      titre: "Projet réseau ",
      description: "Communication entre deux VM",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c4" }, { id: "c5" }, { id: "c6" }],
      language: [{ name: "bla" }, { name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 10,
      titre: "Projet BTS 1",
      description: "Site e-commerce de réservation de plat asiatique",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c3" }, { id: "c4" }, { id: "c5" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 11,
      titre: "Site e-commerce (front)",
      description: "Site e-commerce de vente de produit en tout genre",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c4" }, { id: "c5" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
];
