export const stage = [
   {
      id: 1,
      titre: "Affichage infos clients lors d'un appel",
      description: "affichage d'information client lors de la réception d'un appel téléphonique, avec formulaire afin de remplir les informations du clients",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 2,
      titre: "Interface conversion fichier XML",
      description: "Interface de conversion entrante au format XML afin de mettre à jour une base de donnée",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c4" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 3,
      titre: "Maquette site association airsoft",
      description:
         "Maquette complète côté front d'un site internet d'une association de terrain d'airsoft/paintball/archerytag/laser game, avec une interface agréable et unique (style jeu vidéo) (REACT Vite)",
      categorie: [{ id: "c1" }, { id: "c2" }, { id: "c3" }, { id: "c4" }, { id: "c5" }, { id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 4,
      titre: "SEO/SEA pour entreprises",
      description: "SEO/SEA pour entreprises",
      categorie: [{ id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 5,
      titre: "Formation SEA",
      description: "Formation par Sébastien Rech",
      categorie: [{ id: "c2" }, { id: "c3" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
   {
      id: 6,
      titre: "Projet Agenda",
      description: "Réalisation d'un agenda (côté front), création d'une interface agréable d'un agenda scolaire.",
      categorie: [{ id: "c6" }],
      language: [{ name: "bla" }],
      imageLink: "blablablabla",
   },
];
